// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginUser struct {
	UserOrEmail string `json:"user_or_email"`
	Password    string `json:"password"`
}

type NewPost struct {
	Contents []*NewPostContent `json:"contents"`
	Caption  string            `json:"caption"`
	Username string            `json:"username"`
}

type NewPostContent struct {
	Path string `json:"path"`
	Type string `json:"type"`
}

type NewUser struct {
	Username   string `json:"username"`
	FullName   string `json:"full_name"`
	Email      string `json:"email"`
	Password   string `json:"password"`
	IsGoogle   bool   `json:"is_google"`
	IsVerified bool   `json:"is_verified"`
}

type PostPagged struct {
	Posts     []*Post `json:"posts"`
	Nextposts string  `json:"nextposts"`
	Hasnext   bool    `json:"hasnext"`
}

type VerificationInput struct {
	Token string `json:"token"`
	Email string `json:"email"`
}

type ResendVerification struct {
	Email string `json:"email"`
}

type ResetPassword struct {
	Token    string `json:"token"`
	Password string `json:"password"`
}
